### PR TITLE
Fixing snapshot so photo is delivered in notification. 

### LINKED ISSUE #6: Motion will not send a Notification with Picture
A motion is detected but no notification with lastsnap will shown.
Camera is in the same home kit room

### PR DESCRIPTION
**Pull request by ayman**
Fixes #6. Removing `snapshot_path` from config as it is now autoset to last snap recorded by `motion`. Last picture now delivered in notification. Plus removed rogue comma in array.

### CODE REVIEW

**Comment by ayman** [comment]
I should point out:
```
# Note: A symbolic link called lastsnap.jpg created in the target_dir will always
# point to the latest snapshot, unless snapshot_filename is exactly 'lastsnap'
```
this never worked on my config, hence this p/r.

**Comment by Minims** [comment]
Can you give your motion package and raspbian version so i can make a new try too.

**Comment by ayman** [comment]
On a Raspberry Pi ZeroW. 

```
pi@pi0:/tmp $  cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@pi0:/tmp $ motion -h
motion Version 4.0, Copyright 2000-2016 ...
```
The target dir in the motion config is `/home/pi/cam` and the chmod of that dir is 777 with motion being run with sudo.   So I have no idea why it doesn't writing the symbolic link.   

This edit just sets the snapshot to the last thing in the motion-pipe dynamically.

**Comment by Minims** [comment]
I have tried on a Stretch, it seems symlink doesn't work here. I have tried running motion as pi user, but I have the same issue.

**Pull request merged**
